spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:movieBot;DB_CLOSE_DELAY=-1
    username: sa
    password:
    
  jpa:
    show-sql: true


twilio:
  account:
    sid: AC9f65f767c73529ca7acbf23ecd8a8910
  auth:
    token: 37763dd078ec72defe754a20fcd25732
  service:
    id: VA7a1b2e1c1e800149264a5ed5053dc19f
